#!/bin/bash
if [ "$#" -lt  "1" ]
   then
   git config story.id
   exit 0
fi

if [ "$1" = "--unset" ]
   then
   git config --unset story.id
   exit 0
fi
	
git config story.id $1
echo "set story id: $1"

git story-install-hooks
